### ISSUE TITLE
VST3 plugin does not integrate with Audacity on MacOS

### ISSUE THREAD

**Issue by nikodenn** [bboettcher3/gRainbow#100]
Steps to reproduce:
1. Copy plugin into the /Library/Audio/Plug-Ins/VST3 folder
2. Remove quarantine attribute from the plugin
3. Run Audacity and open Plugin Manager (Effect->Plugin Manager in Audacity main menu)
==>
Plugin manager of Audacity does not find the plugin (BTW, Audacity usually does plugin rescan automatically on startup when some new plugin has been put into the /Library/Audio/Plug-Ins/VST3 folder, but not in this exact case)

 - Audacity 3.6.4
 - OS: MacOS Ventura 13.7
 - gRainbow version 1.0.3

**Comment by bboettcher3** [comment]
@nikodenn it probably isn't finding it because gRainbow is a VST instrument, not an effect. It takes MIDI input to produce its sounds. As far as I understand, audacity doesn't support VST instruments.

**Comment by nikodenn** [comment]
> @nikodenn it probably isn't finding it because gRainbow is a VST instrument, not an effect. It takes MIDI input to produce its sounds. As far as I understand, audacity doesn't support VST instruments.

Yeah, this seems to be a reason. Thank you.
