### ISSUE TITLE
MacOS (ARM): crash when changing image while playing MIDI

### ISSUE THREAD

**Issue by bboettcher3** [bboettcher3/gRainbow#53]
Reported from a user. Still being investigated, can't seem to reproduce on Windows..

**Comment by atsushieno** [comment]
Maybe it's not surprising, I hit the crash near `TODO: fix bug where gNote is null here in Debug`:

<img width="1226" alt="image" src="https://github.com/bboettcher3/gRainbow/assets/53929/046199cb-302c-49f5-83c9-b3a47c00b106">

(M2 mac, Standalone app, build at a20ba72.)

**Comment by bboettcher3** [comment]
May be a duplicate of #58 , if not I can reopen
