### ISSUE TITLE
LV2 target?

### ISSUE THREAD

**Issue by mxmilkiib** [bboettcher3/gRainbow#54]
Hi, I was wodnering if an LV2 plugin format target/release could be supported please?

**Comment by bboettcher3** [comment]
Found on Jatin Chowdhury's blog :joy:: 

<img width="573" alt="image" src="https://github.com/bboettcher3/gRainbow/assets/13266420/641dc23d-5649-4e37-a563-4bbdb31237e6">


So yep, I'll look into getting that put into the releases for you!

**Comment by bboettcher3** [comment]
Added to https://github.com/bboettcher3/gRainbow/releases/tag/v0.2.2 :)

**Comment by mxmilkiib** [comment]
Awesome, thanks! P.S. LV2 is multiplatform
