### ISSUE TITLE
allow the choice of install location in install wizard

### ISSUE THREAD

**Issue by Woolton** [bboettcher3/gRainbow#55]
The install wizard does not allow for the choice of install location. Upon installation, I cannot find my installation of the program either, it isn't in the default steinberg folder, nor in my custom VST folders.

The install wizard doesn't show the install location either, this would be very helpful to find the program in less vigorously indexed folders, like programfiles

**Comment by NeuKatalYst** [comment]
It's a VST3, so it has no choice but to go to Common Files > VST3

**Comment by bboettcher3** [comment]
I'll work on adding custom install locations for the standalone (and might as well do VST3 too), but as @NeuKatalYst said, the VST3 should almost always go with the others in "Program Files/Common Files/VST3" on windows

**Comment by scorch42** [comment]
Where is the standalone currently installed? I cannot find it either...

**Comment by NeuKatalYst** [comment]
Iirc, there is no standalone: only a VST3

**Comment by bboettcher3** [comment]
The standalone should be installed in Program Files/strangeloops/gRainbow.exe as my company name is Strange Loops

I should have made a note in the installer to show the install location, I'll fix that in the next release.

**Comment by Woolton** [comment]
I see, the VST3 folder stipulation is fine. It's easy enough to migrate other VSTs over
