### ISSUE TITLE
Crashes Ableton 11 on Mac M2Pro

### ISSUE THREAD

**Issue by groundloop71** [bboettcher3/gRainbow#56]
Both the vst and au versions crash Ableton 11 on Mac M2 Pro Osx Ventura 13.4. The GUI seems to work but no sound from both the plugin and Ableton. I had to force quit Ableton. I had to codesign everything otherwise Ableton said the plugins were damaged and the standalone won't run. I used these lines in terminal: 
sudo xattr -rd com.apple.quarantine 
sudo codesign -fs -
if this can be of any help.
Thanks in advance for eventual help/solutions

**Comment by bboettcher3** [comment]
Consolidating into #58 , closing!

**Comment by bboettcher3** [comment]
@groundloop71 Just released a code signed version that should fix this, let me know if it persists!

**Comment by groundloop71** [comment]
@bboettcher3 it seems it works :) Thank you.
