### ISSUE TITLE
component cannot be opened in OS Monterey 12.6.5

### ISSUE THREAD

**Issue by notebynote** [bboettcher3/gRainbow#57]
"gRainbow.component" cannot be opened because Apple cannot search for malware in it.

**Comment by bboettcher3** [comment]
Yup, I'll get around to code signing things at some point, I just have to pull the trigger on the Mac developer license. One user gave these terminal commands to get around the malware check:
```
sudo xattr -rd com.apple.quarantine
sudo codesign -fs -
```

**Comment by notebynote** [comment]
Hi Brady,
thanks, but as I do not know if this command is any harmful for my system I
will not use it :D
I wait until your component will run on Monterey and above.

cheers, Thomas

Am Mo., 5. Juni 2023 um 17:32 Uhr schrieb Brady Boettcher <
***@***.***>:
