### ISSUE TITLE
error with visual c++ and other

### ISSUE THREAD

**Issue by lil-millp** [bboettcher3/gRainbow#64]
Hi
Everything worked fine, but at some point problems started
I tried to reinstall microsoft visual, installed all versions, replaced the vcruntime140 file, checked the computer using sfc and dism and everything was empty
The rest of the programs work fine
What could be the problem?

The error occurs at a random moment when the last pressed key starts playing automatically
Or when rendering an audio file

I tried it in FL and Ableton, the programs are closing

Screenshot of the error
https://imgur.com/a/b7NiZPX

I really liked the plugin in my work, I would like to use it!

**Comment by lil-millp** [comment]
The error occurs at a random moment when the last pressed key starts playing automatically
Or when rendering an audio file

**Comment by bboettcher3** [comment]
Hi, thanks for the details! Could you give a few more about what you mean when you say "starts playing automatically" and what you mean by "rendering" (e.g, drawing visual rainbows)? I'll try and find fixes soon if I'm able to reproduce the crashes.

**Comment by lil-millp** [comment]
About automatic playback. I don't know how it happened. One of the automatic playback methods is shown on the video.
Rendering in plane FL Studio "Quick render as audio clip" Any "File - Export - Wav/mp3"

https://www.youtube.com/watch?v=1EkDWHxl34I
Timecodes in the description

If you need any more information, be sure to write.
grainbow 0.2.3
windows 10 ltsc
![изображение](https://github.com/bboettcher3/gRainbow/assets/89031429/631012ea-e761-4f75-8fb5-8c22aff1406d)

**Comment by lil-millp** [comment]
I do not know if you will be able to reproduce this error. I think it's about the PC itself.
Although I didn't touch the system files, windows installed ~3 months ago.

**Comment by bboettcher3** [comment]
Thanks for the video, that helps a lot! I'm 99.9% sure this isn't related to your PC, it just seems like a code bug that I'll try and track down. Will keep you posted.

**Comment by lil-millp** [comment]
If this is the case and the problem is not in my PC, it will be very good! This plugin helps me in my non-standard creativity to do non-standard things. 🤓🤓

**Comment by bboettcher3** [comment]
@lil-millp Just found and fixed the rendering crash bug, still trying to reproduce the playback crash though

**Comment by lil-millp** [comment]
If possible, you can send me a "beta type" and I will try it for this error.

**Comment by bboettcher3** [comment]
https://github.com/bboettcher3/gRainbow/suites/13522774245/artifacts/743435603

**Comment by lil-millp** [comment]
Everything works! I hope that forever, ahah.
Thank you very much for this plugin!

**Comment by bboettcher3** [comment]
Great! Feel free to open new issues if you find them :)
