### ISSUE TITLE
Cant launch with GCC less than 13

### ISSUE THREAD

**Issue by gcentauri** [bboettcher3/gRainbow#89]
**Describe the bug**

None of the options can launch due to an older version of libstdC++

`./Standalone/gRainbow: /lib/x86_64-linux-gnu/libstdc++.so.6: version 'GLIBCXX_3.4.32' not found (required by ./Standalone/gRainbow)`

**Desktop (please complete the following information):**
 - OS: Ubuntu 22.04 (Pop!_OS
 - gRainbow v1.0.3

Is it possible to build with an older version of GLIBC? or can those shared libraries get included somehow? My OS isn't all that old but the GCC version 13 that seems required isn't available. I wasn't able to find instructions on how to build (I'm not familiar with CMAKE and was getting errors trying to build from source as well)

I bought gRainbow just today after watching some demos and figured it would work :) I don't mind some fiddling but it would be great to get it working!

**Comment by sjfricke** [comment]
same as https://github.com/StrangeLoopsAudio/gRainbow/issues/87 and https://github.com/StrangeLoopsAudio/gRainbow/issues/85

I built it locally for older GLBIC here  https://github.com/StrangeLoopsAudio/gRainbow/releases/tag/v1.0.3

We are working on fixing the CI flow that publishes it to not use such a new binary

**Comment by gcentauri** [comment]
apologies, I didn't notice those issues were due to the same underlying cause. I'll give the older GLIBC a shot, also i will look into alternative ways to install the proper version without distro support :) thanks for the answer

**Comment by bboettcher3** [comment]
@gcentauri if it wasn't clear, you can download a working version from the tag v1.0.3 from the link above :) We'll work on getting this fixed in CI, and let us know if the new download still doesn't work for you.

**Comment by gcentauri** [comment]
@bboettcher3 - yep the patch version works just fine! playing around with it now. good stuff <3 i haven't played much with granular since a fine little program called kluppe from log ago
