### ISSUE TITLE
VST3 failed to load in Bitwig on Fedora Silverblue 39

### ISSUE THREAD

**Issue by sul-umberto** [bboettcher3/gRainbow#90]
VST3 failed to load in Bitwig.
When i try to start the Plugin, i get the following error:
/usr/lib/x86_64-linux-gnu/libstdc++.so.6: version GLIBCXX_3.4.32 not found

The Standalone-Version of gRainbow works flawless!

 - OS: Fedora Silverblue 39
 - gRainbow version 1.0.3

**Comment by bboettcher3** [comment]
@sul-umberto this is the same issue as https://github.com/StrangeLoopsAudio/gRainbow/issues/89, please check it out for the solution!

**Comment by sul-umberto** [comment]
bboettcher3 the patched version works!

many thanks!
